version: "3"
services:
  zenaton_automated_reminder_emails_sample_project:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    volumes:
      - ..:/app
    ports:
      - "4000:4000"
    env_file:
      - ../.env
